name = "docker-mirror"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "libcuda.so"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
    { pattern = "docker.oci.mchappy.online", custom_domain = true },
    { pattern = "quay.oci.mchappy.online", custom_domain = true },
    { pattern = "gcr.oci.mchappy.online", custom_domain = true },
    { pattern = "k8s-gcr.oci.mchappy.online", custom_domain = true },
    { pattern = "k8s.oci.mchappy.online", custom_domain = true },
    { pattern = "ghcr.oci.mchappy.online", custom_domain = true },
    { pattern = "cloudsmith.oci.mchappy.online", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "staging.oci.mchappy.online", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
